site_name: Varssos MkDocs
nav:
  - Home: index.md
  - About: about.md
  - Medium: medium.md
  - Linux: linux/index.md
  - Linux test: 
    - linux/index.md
    - Admin tools: linux/admin_tools.md
    - abc: linux/abc.md
    - 'Shell tools':
      - linux/shell_tools/nice.md
      - linux/shell_tools/fzf.md
  - Version control:
    - version_control/index.md
    - gerrit: version_control/gerrit/index.md
    - git: version_control/git/index.md
  - Python:
    - python/index.md


theme:
  name: material
  icon:
    logo: fontawesome/solid/v
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    # - navigation.tabs
    # - navigation.sections
    - navigation.indexes
    - content.code.copy
    - content.code.select
    - content.code.annotate


plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/

# markdown_extensions:
#   - toc:
#       toc_depth: 2-3
#       permalink: true

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true