site_name: Varssos MkDocs
# nav:
#   - Home: index.md
#   - About: about.md
#   - Apps:
#     - apps/index.md
#     - Brave: apps/brave.md
#   - Ansible:
#     - ansible/index.md
#     - ansible-vault: ansible/ansible-vault.md 
#   - Docker:
#     - docker/index.md
#     - Install docker: docker/install_docker.md
#   - Embedded linux:
#     - embedded_linux/index.md
#     - Android: 
#       - embedded_linux/android/index.md
#       - AIDL: embedded_linux/android/aidl.md
#       - Services: embedded_linux/android/services.md
#   - ESP:
#     - esp/index.md
#     - ESP USB chip drivers: esp/esp_usb_chip_drivers.md
#     - ESPHome: 
#       - esp/esphome/index.md
#       - Getting started with ESPHome: esp/esphome/getting_started_esphome.md
#       - Encountered problems with ESPHome: esp/esphome/esphome_encountered_problems.md
#       - Wifi Fallback: esp/esphome/wifi_fallback.md
#   - Home server:
#     - home_server/index.md
#     - AFFiNE: home_server/affine.md
#     - AppFlowy: home_server/appflowy.md
#     - Homeassistant: home_server/homeassistant.md
#     - Immich: home_server/immich.md
#     - Nginx proxy manager: home_server/nginx_proxy_manager.md
#     - Pi-hole: home_server/pi-hole.md
#   - Medium: medium.md
#   - Network:
#     - network/index.md
#     - DoIP:
#       - DoIP general information: network/doip/doip_general_information.md
#   - Linux: 
#     - linux/index.md
#     - Concepts:
#       - linux/concepts/index.md
#       - POSIX: linux/concepts/posix.md
#     - System administration:
#       - linux/system_administration/index.md
#       - Admin tools: linux/system_administration/admin_tools.md
#       - Cron: linux/system_administration/cron.md
#       - GRUB: linux/system_administration/grub.md
#       - PC troubleshooting: linux/system_administration/pc_troubleshooting.md
#       - Systemd service: linux/system_administration/systemd_service.md
#       - Users: linux/system_administration/users.md
#     - Package management system:
#       - linux/package_management_system/index.md
#       - apt: linux/package_management_system/apt.md
#       - Debian package management system: linux/package_management_system/debian_package_management_system.md
#       - Downgrade apps: linux/package_management_system/downgrade_apps.md
#       - Install deb packages from file: linux/package_management_system/install_deb_from_file.md
#     - Hardware:
#       - linux/hardware/index.md
#       - HID: linux/hardware/hid.md
#       - Nvidia: linux/hardware/nvidia.md
#       - Printers:
#         - linux/hardware/printers/index.md
#         - Brother: linux/hardware/printers/brother.md
#       - Usb hub: linux/hardware/usb_hub.md
#       - Usb linux: linux/hardware/usb_linux.md
#       - Usb network speed: linux/hardware/usb_network_speed.md
#     - Desktop and multimedia:
#       - linux/desktop_and_multimedia/index.md
#       - GUI on Linux: linux/desktop_and_multimedia/gui_on_linux.md
#       - Pulseaudio: linux/desktop_and_multimedia/pulseaudio.md
#     - Security:
#       - linux/security/index.md
#       - Certificates: linux/security/certificates.md
#       - SELinux: linux/security/selinux/index.md
#     - Performance tuning:
#       - linux/performance_tuning/index.md
#       - swap: linux/performance_tuning/swap.md
#     - Shell tools:
#       - linux/shell_tools/index.md
#       - Common:
#         - linux/shell_tools/common/index.md
#         - awk: linux/shell_tools/common/awk.md
#         - curl: linux/shell_tools/common/curl.md
#         - find: linux/shell_tools/common/find.md
#         - grep: linux/shell_tools/common/grep.md
#         - hexdump: linux/shell_tools/common/hexdump.md
#         - md5sum: linux/shell_tools/common/md5sum.md
#         - mv: linux/shell_tools/common/mv.md
#         - nice: linux/shell_tools/common/nice.md
#         - sed: linux/shell_tools/common/sed.md
#         - sha256sum: linux/shell_tools/common/sha256sum.md
#         - tar: linux/shell_tools/common/tar.md
#       - Modern:
#         - linux/shell_tools/modern/index.md
#         - expect: linux/shell_tools/modern/expect.md
#         - fzf: linux/shell_tools/modern/fzf.md
#         - notify-send: linux/shell_tools/modern/notify-send.md
#         - tmux: linux/shell_tools/modern/tmux.md
#       - Random shell exercises: linux/shell_tools/random_shell_exercises.md
#     - Storage:
#       - linux/storage/index.md
#       - mdadm: linux/storage/mdadm.md
      
#   - Version control:
#     - version_control/index.md
#     - gerrit: version_control/gerrit/index.md
#     - git: version_control/git/index.md
#   - Python:
#     - python/index.md
#   - Reverse engineering:
#     - reverse_engineering/index.md
#     - Reverse engineering tools: 
#       - reverse_engineering/reverse_engineering_tools/index.md
#       - ExifTool: reverse_engineering/reverse_engineering_tools/exiftool.md
#       - ImHex: reverse_engineering/reverse_engineering_tools/imhex.md
#     - File formats:
#       - reverse_engineering/file_formats/index.md
#       - JPEG: reverse_engineering/file_formats/jpeg.md
    


theme:
  name: material
  icon:
    logo: fontawesome/solid/v
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.indexes
    # - toc.integrate # Table of contents integrated on the left
    - navigation.tabs.sticky
    - content.code.copy
    - content.code.select
    - content.code.annotate


plugins:
    - plantuml:
        puml_url: https://www.plantuml.com/plantuml/
    - search
    # - awesome-pages

# markdown_extensions:
#   - toc:
#       toc_depth: 2-3
#       permalink: true

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - tables
  - md_in_html
